### ISSUE TITLE
validation error for ChatAnthropic

### ISSUE THREAD

**Issue by therealmmk** [aws-samples/amazon-kendra-langchain-extensions#16]
running kendra_retriever_anthropic.py results in validation error for ChatAnthropic
sagemaker-user@studio$ python kendra_retriever_anthropic.py 
Traceback (most recent call last):
  File "/home/sagemaker-user/amazon-kendra-langchain-extensions/kendra_retriever_samples/kendra_retriever_anthropic.py", line 56, in <module>
    chain = build_chain()
  File "/home/sagemaker-user/amazon-kendra-langchain-extensions/kendra_retriever_samples/kendra_retriever_anthropic.py", line 13, in build_chain
    llm = Anthropic(temperature=0, anthropic_api_key=ANTHROPIC_API_KEY)
  File "/opt/conda/lib/python3.9/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ChatAnthropic
__root__
  __init__() got an unexpected keyword argument 'api_url' (type=type_error)

**Comment by rohitvincent** [comment]
any update on this issue? I am getting the same error.

**Comment by MithilShah** [comment]
closed because inactive
